### ISSUE TITLE
Ghost Shells can be used to dupe Items

### ISSUE THREAD

**Issue by teoWei** [Kira-NT/sync-fabric#13] opened 2021-10-08 12:34 UTC
When no clones of your self exist and while a shell is being constructed, going into a Shell Storage and switching to the body you were switching from will instantly finish the shell that is being constructed and dupe everything in the shell you were switching from to the newly constructed shell. For while multiple shells are being constructed, I observed that it choses a random shell to dupe and once there's 2 fully constructed shell, dupe will stop working unless the shell dies until 1 remain.

**Comment by Kira-NT** [comment] 2021-10-08 17:49
Could you provide me with some screenshots and all the actions needed to reproduce the issue, please? Because I don't quite understand what you mean by 

> switching to the body you were switching from

**Comment by teoWei** [comment] 2021-10-10 01:36
I just did some testing again and I found out, you're not supposed to be able to switch to the shell you're currently in. Somehow the first time I tried the mod, it allowed me to switch to the shell that I'm currently inside of but have no idea how did I get to be able to do that.
(In this image, I don't have any shell constructed, just the original shell that I'm inside of.)
![image](https://user-images.githubusercontent.com/54856793/136678085-6635189e-02ec-4baf-8bff-af2ff6c5b87e.png)

I'm not sure why but the dupe seems to only work with this specific shell constructor. It doesn't even need to be constructing the shell, it just needs to have your sample and the dupe would just work. I'm also not sure how did I get this specific shell constructor to have special abilities. I tried breaking and replacing it, it'll still dupe.
![image](https://user-images.githubusercontent.com/54856793/136678621-3b16176b-5fc8-4f1f-8183-6ff17330310a.png)

But this is how I duped while being able to switch to a shell I'm currently inside of and with a shell constructor with special abilities:
1) Make sure you have no clones/shells, just the one you're currently in.
![image](https://user-images.githubusercontent.com/54856793/136678674-886a3a96-16af-476d-8275-42085c43a375.png)
2) Start construction of a shell in THE shell constructor.(I gave it my sample, you can't see it because it's not constructing. It doesn't need to be constructing the body to dupe, it just needs your sample.)
![image](https://user-images.githubusercontent.com/54856793/136678709-097af57b-8e0e-425e-8d40-e2286afecb69.png)
3) Put yourself into a shell storage.
![image](https://user-images.githubusercontent.com/54856793/136678712-2948ff7a-4f37-4bc7-8b7c-31414c7a9554.png)
4) Switch to the current body you're in.
![image](https://user-images.githubusercontent.com/54856793/136678713-e3559e52-3463-476d-932f-50e10c7c8102.png)
5) You should be in the shell storage that you were in but with you and a shell of you in it. The shell in the shell constructor should be gone and both you and the other shell should have similar inventory.
![image](https://user-images.githubusercontent.com/54856793/136678725-23cbb174-547c-4de8-b886-20b7c1112e35.png)
6) You can switch off the power source to the shell storage and kill the shell, it should drop it's inventory when it dies. (It also drops the xp too.)
![image](https://user-images.githubusercontent.com/54856793/136678736-5b5c60bf-3a36-4f4f-8b57-b3117ba89377.png)

**Comment by Kira-NT** [comment] 2021-10-10 04:48
> I found out, you're not supposed to be able to switch to the shell you're currently in

Yeah, that's why I was confused. Radial menu contains non-active shells only. Therefore, the main question is how did you get one of those?

Can you reproduce this behavior in any world? Or does it only work in this one with this specific shell storage?

**Comment by teoWei** [comment] 2021-10-10 12:44
I'm not sure how I gotten into this predicament. Also btw, it only works with that specific shell constructor, not shell storage.

**Comment by Kira-NT** [comment] 2021-10-10 13:29
May I ask you for a world download?

**Comment by teoWei** [comment] 2021-10-10 23:03
Yea, sure.
https://www.mediafire.com/file/1eysz6syjggrz5d/test+0_1_0.zip/file

**Comment by Kira-NT** [comment] 2021-10-11 15:14
Thanks a lot, it was really handy to understand what's going there!

The problem is the shell you're trying to sync with does not really exist *("ghost shells may appear from time to time due to some unlikely events, e.g., chunk being unloaded mid-tick, server crashing, and so on. Sadly, there's not too much I can do about it")*, but its presence in your radial menu allows you to initiate the syncing process with a shell at the same coords that has not been constructed yet.

The syncing process itself fails *(that's why you don't move to another location)*, but a copy of yourself has been already stored in the shell storage by that time.

Good news are the issue is not reproducible in the latest dev builds *(I've been doing a lot of refactoring lately)*. The syncing process will fail with the message "The selected shell cannot be found", and no duped shell will be created

**Comment by teoWei** [comment] 2021-10-11 19:47
That's great!

**Comment by Kira-NT** [comment] 2021-11-13 13:56
Has been fixed in [`mc1.17.1-2.0`](https://github.com/Kir-Antipov/sync-fabric/releases/tag/mc1.17.1-2.0)

**Closed as completed by Kira-NT** 2021-11-13 13:56 UTC
Labels: bug
