### ISSUE TITLE
Shell is not being constructed

### ISSUE THREAD

**Issue by BillyBro** [Kira-NT/sync-fabric#7] opened 2021-09-09 19:08 UTC
i have downloaded this mod for 1.17.1 because i thought it would be great. dont get me wrong its a cool mod and works for loads of others but for me when i force the pigs to run for eternity and right click nothing happens. its like i dont have a body to clone lmao. any help would be appreciated.

**Comment by Kira-NT** [comment] 2021-09-09 19:25
Welp, too little info. I don't know version of the mod you've installed, don't know which other mods you're using, don't know version of fabric api and fabric loader. Didn't even see a setup you've considered as non-working.

So, at the moment I cannot provide any help, because the issue is not reproducible

**Comment by Kira-NT** [comment] 2021-09-11 10:00
If you still need help, provide me with the requested information, please; otherwise, I'll have to close this issue as invalid.

**Comment by Kira-NT** [comment] 2021-10-09 00:44
Didn't hear from you for a while, so I'm gonna close the issue, because it's not reproducible the way you described it

**Closed as completed** 2021-10-09 00:44 UTC
Labels: invalid
